Django_energy/accounts/urls.py
from django.urls import path

from .views import SignUpView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

Django_energy/blog/urls.py
from django.urls import path
from django.contrib import admin
from blog.views import CategoryListView, PostByCategoryView
from .views import (
    BlogListView,
    BlogUpdateView,
    BlogDetailView,
    BlogCreateView,
    BlogDeleteView,
)
urlpatterns = [
    path('post/<int:pk>/delete/',BlogDeleteView.as_view(), name='post_delete'),
    path('post/new/', BlogCreateView.as_view(), name='post_new'),
    path('post/<int:pk>/', BlogDetailView.as_view(), name='post_detail'),
    path('post/<int:pk>/edit/', BlogUpdateView.as_view(), name='post_edit'),
    path('admin/', admin.site.urls),
    # path('accounts/logout/', CategoryListView.as_view(), name='category_list'),
    # path('accounts/login/', CategoryListView.as_view(), name='category_list'),
    path('', CategoryListView.as_view(), name='category_list'),
    path('<str:slug>/', PostByCategoryView.as_view(), name='post-by-category'),     
]


Django_energy/blog_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')), # новое добавление
    path('', include('blog.urls')),
    
]


Django_energy/accounts/models.py
from django.db import models

# Create your models here.

Django_energy/blog/models.py
from django.db import models
from django.urls import reverse # Новый импорт
from django_quill.fields import QuillField
from mptt.models import MPTTModel, TreeForeignKey

class Post(models.Model):
    title = models.CharField(max_length=100, verbose_name='Название')
    slug = models.SlugField(max_length=150)
    category = TreeForeignKey('Category', on_delete=models.PROTECT, related_name='posts', verbose_name='Категория')
    content = models.TextField(verbose_name='Содержание')


    
    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])
    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'
# Модель категории
class Category(MPTTModel):
    title = models.CharField(max_length=50, unique=True, verbose_name='Название')
    parent = TreeForeignKey('self', on_delete=models.PROTECT, null=True, blank=True, related_name='children',db_index=True, verbose_name='Родительская категория')
    slug = models.SlugField(unique=True, null=False, default='test')

    class MPTTMeta:
        order_insertion_by = ['title']

    class Meta:
        unique_together = [['parent', 'slug']]
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    # def get_absolute_url(self):
    #     return reverse('post-by-category', args=[str(self.slug)])

    def __str__(self):
        return self.title
# Модель статья
class Article(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='категория')
    # другие поля ....


class QuillPost(models.Model):

    content = QuillField()

Django_energy/blog/forms.py
from django import forms
from .models import QuillPost

class QuillPostForm(forms.ModelForm):
    class Meta:
        model = QuillPost
        fields = (
            'content',
        )

Django_energy/accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

Django_energy/blog/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView # новое
from django.urls import reverse_lazy # импортируем новые методы
from django import forms
from .models import Post,QuillPost, Category

class QuillPostForm(forms.ModelForm):
    class Meta:
        model = QuillPost
        fields = (
            'content',
        )


class BlogListView(ListView):
    model = Post
    template_name = 'category_list.html'


class BlogDetailView(DetailView):
    model = Post
    template_name = 'post_detail.html'
    fields = ['title', 'category', 'content']


class BlogCreateView(CreateView):
    model = Post
    template_name = 'post_new.html'
    fields = ['title', 'category', 'content']


class BlogUpdateView(UpdateView):
    model = Post
    template_name = 'post_edit.html'
    fields = ['title', 'category', 'content']


class BlogDeleteView(DeleteView): # Создание нового класса
    model = Post
    template_name = 'post_delete.html'
    success_url = reverse_lazy('category_list')

class CategoryListView(ListView):
    model = Category
    template_name = "category_list.html"


class PostByCategoryView(ListView):
    context_object_name = 'posts'
    template_name = 'post_list.html'

    def get_queryset(self):
        self.category = Category.objects.get(slug=self.kwargs['slug'])
        queryset = Post.objects.filter(category=self.category)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.category
        return context

Django_energy/templates/base.html
{% load static %}
<html>
  <head>
    <title>Django blog</title>
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400"
    rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
  
  </head>
  <body>
    <div class="container">
      <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <img src="{% static 'media/images/greenWind.jpg' %}" style="width:100px;" alt="My image">
        
          <div class="container-fluid">
          <h1 ><a class="text-dark" href="{% url 'category_list' %}">Главная</a></h1>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
            <div class="collapse navbar-collapse" id="navbarText">
                            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item dropdown">
                 <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">услуги</a>
                 <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                   <!--<a class="dropdown-item" href="../../web">веб-разработка</a>-->
                   <a class="dropdown-item" href="../../ecology">Экологический кризис энергетики</a>
                   <a class="dropdown-item" href="../../alt_energy">Альтернативная энергия</a>
                   <a class="dropdown-item" href="../../fuel">Кризис топливных ресурсов</a>
                 </div>
               </li>
               {% if user.is_authenticated %}
               <li class="nav-item">
                <a class="nav-link" href="{% url 'post_new' %}">Разместить объявление</a>
              </li>
              {% endif %}

               <li class="nav-item">
                 <a class="nav-link" href="{% url 'signup' %}">Регистрация</a>
               </li>
             </ul>
             <p class="navbar-text">
              {% if user.is_authenticated %}
              <div class="navbar">Привет {{ user.username }}!</div>
              <div class="nav-right">
             <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
              </div>
              {% else %}
               <a class="nav-link" href="{% url 'login' %}">Войти</a>
      {% endif %}
            </p>
           </div>
          </div>
         </nav>
     </header>
    </div>
    
    {% block content %}
    {% endblock content %}
  </body>
  <style>
    body {
      background-size: 60%;
      background-repeat: no-repeat;
  }
</style>
</html>

Django_energy/templates/category_list.html
{% extends "base.html" %}
{% load mptt_tags %}
      
{% block title %}Список категорий{% endblock %}

{% block content %}
{% load static %}
<div class="container">
  <div class="row">
    <div class="col-md-6">
      
     
      
        
        <div class="list-group" class="center" class="outside" style="max-width: 400px;">
          {% recursetree object_list %}
        
        <a href="{{node.slug}}" class="list-group-item list-group-item-action" aria-current="true">{{node.title}}</a>
          {% if not node.is_leaf_node %}
                      <div class="children">
                          {{ children }}
              </div>
          {% endif %}
        {% endrecursetree %}
      </div>
    </div> 
    <div class="col-md-6">
      <img src="{% static 'media/images/image.png' %}" width="100%" alt="My image">
     <h5>На нашем сайте, Вы, можете оставить предложение по решению энергетических проблем, таких как:
      Проблемы топливных ресурсов, Экологический кризис энергетики, а также предложить свой вариант альтернативного возобновляемого источника энергии.
     </h5>
    </div>
  </div>
</div>
        {% endblock  %}

 

Django_energy/templates/form_view.html
<form action="" method="POST">{% csrf_token %}
    {{ form.content }}
</form>

Django_energy/templates/home.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block content %}
  {% for post in object_list %}
  <div class="post-entry">
    <h2><a href="{% url 'post_detail' post.pk %}">{{ post.title }}</a></h2>
    <p>{{ post.body }}</p>
  </div>
  {% endfor %}
{% endblock content %}

Django_energy/templates/post_delete.html
{% extends 'base.html' %}

{% block content %}
    <h1>Delete post</h1>
    <form action="" method="post">{% csrf_token %}
      <p>Are you sure you want to delete "{{ post.title }}"?</p>
      <input type="submit" value="Confirm" />
    </form>
{% endblock content %}

Django_energy/templates/post_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="text-center">
  <div class="post-entry">
    <h2>{{ post.title }}</h2>
    <p>{{ post.content }}</p>
    <p>Идею предложил: {{ user.username }}</p>
  </div>
  <a href="{% url 'post_edit' post.pk %}" class="btn btn-success m-3" role="button">Изменить объявление</a>
<br>
  <a href="{% url 'post_delete' post.pk %}" class="btn btn-danger" role="button">Удалить объявление</a>
</div>
{% endblock content %}

Django_energy/templates/post_edit.html
{% extends 'base.html' %}

{% block content %}
    <h1>Edit post</h1>
    <form action="" method="post">{% csrf_token %}
      {{ form.as_p }}
    <input type="submit" value="Update" />
</form>
{% endblock content %}

Django_energy/templates/post_list.html
{% extends "base.html" %}
{% block title %}Посты из категории {{title}}{% endblock %}

{% block content %}
<main>

		
	  
    <section>
	<div class="container">
	    <h1 class="text-center">Посты из категории {{title}}</h1>
	</div>
    </section>
	
		{% for post in object_list%}
		<div>

				<div class="card text-dark  mb-3" id="content">
			  <div class="card-header text-center">  <h2><a  href="{% url 'post_detail' post.pk %}">{{ post.title }}</a></h2></div>
			  <div class="card-body">
				
				
			<p class="card-text text-center">{{ post.content }}</p>
		  </div>
		</div>
		  </div>
			  {% endfor %}
		  
		  
	  </main>
	  {% endblock %}
	  

Django_energy/templates/post_new.html
{% extends 'base.html' %}

{% block content %}
<div class="text-center">
  <div class="post-entry">
    <h2>{{ post.title }}</h2>
    <p>{{ post.content }}</p>
  </div>
    <h1>Размещение объявления</h1>
   
    <div class="form_new">
      <form action="" method="post">
        {% csrf_token %}
        <p>
      <label for="id_title">Название:</label>
      <input class="form-control" type="text" name="title" maxlength="100" required="" id="id_title">
      
      
    </p>
  
    
    <p>
      <label for="id_category">Категория:</label>
      <select class="form-select" name="category" required="" id="id_category">
    <option value="" selected="">Выберите категорию</option>
  
    <option value="2"> Data-Science</option>
  
    <option value="1"> repetitor</option>
  
    <option value="3"> веб-разработка</option>
    <option value="4"> Кризис топливных ресурсов</option>
  </select>
      
      
    </p>
  
    
    <p>
      <label for="id_content">Содержание:</label>

      <div class="form-floating">
        <textarea style="height: 250px" name="content" rows="10" class="form-control" placeholder="Leave a comment here" id="id_content"></textarea>
        
      </div>
      
        
      
    </p>
        
  
        <input type="submit" class="btn btn-success m-3" value="Сохранить">
      </form>
    </div>
{% endblock content %}

Django_energy/templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2>Sign up</h2>

<div class="sign_up">
  <form method="post">
    {% csrf_token %}
    <div class="form-floating">
      <input class="form-control" type="text" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150" required="" id="id_username">
      <label for="floatingInput">Login</label>
    </div>
    
    <div class="form-floating">
       <input class="form-control" type="password" name="password1" autocomplete="new-password" required="" id="id_password1">
      <label for="floatingPassword">Password</label>
    </div>
  
    <div class="form-floating">
       <input class="form-control" type="password" name="password2" autocomplete="new-password" required="" id="id_password2">
      <label for="floatingPassword">Password</label>
    </div>
  
    
    <button class="w-100 btn btn-lg btn-primary" type="submit">Sign up</button>
   
  </form>
  <img src="{% static 'media/images/vector-a-windmill-and-solar-energy-panels.jpg' %}" width="100%" alt="My image">

</div>

 
{% endblock content %}

Django_energy/templates/uslugi.html
{% extends 'base.html' %}

{% block content %}
{% endblock content %}